// 루트 레이아웃 컴포넌트: 모든 페이지에 공통으로 적용되는 최상위 레이아웃
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Geist Sans 폰트 설정: 기본 sans-serif 폰트
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Geist Mono 폰트 설정: 코드용 monospace 폰트
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 메타데이터 설정: SEO 및 브라우저 탭에 표시되는 정보
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 루트 레이아웃: HTML 구조와 폰트 변수를 설정하고 children을 렌더링
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
